-- Script de configuração do banco CGB Granitos
-- Execute este script no MySQL Workbench ou linha de comando

-- Criar o banco de dados
CREATE DATABASE IF NOT EXISTS cgbgranitos;

-- Usar o banco
USE cgbgranitos;

-- Criar tabelas (opcional, pois o sistema cria automaticamente)
-- Mas você pode executar para verificar se está funcionando

CREATE TABLE IF NOT EXISTS USUARIOS (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_USUARIO VARCHAR(100) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    ATIVO TINYINT(1) NOT NULL
);

CREATE TABLE IF NOT EXISTS PEDREIRAS (
    ID_PEDREIRA INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PEDREIRA VARCHAR(100) NOT NULL,
    LOCALIZACAO VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS BLOCOS (
    ID_BLOCO INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_BLOCO VARCHAR(50) NOT NULL,
    ID_PEDREIRA INT NOT NULL,
    METRAGEM_M3 DECIMAL(10,3),
    TIPO_MATERIAL VARCHAR(100),
    VALOR_COMPRA DECIMAL(10,2),
    NUMERO_NOTA_FISCAL VARCHAR(50),
    DATA_ENTRADA DATETIME,
    FOREIGN KEY (ID_PEDREIRA) REFERENCES PEDREIRAS(ID_PEDREIRA)
);

CREATE TABLE IF NOT EXISTS CHAPAS (
    ID_CHAPA INT AUTO_INCREMENT PRIMARY KEY,
    ID_BLOCO_ORIGEM INT NOT NULL,
    TIPO_MATERIAL VARCHAR(100),
    LARGURA DECIMAL(10,2),
    COMPRIMENTO DECIMAL(10,2),
    ESPESSURA DECIMAL(10,2),
    VALOR DECIMAL(10,2),
    DATA_CADASTRO DATETIME,
    FOREIGN KEY (ID_BLOCO_ORIGEM) REFERENCES BLOCOS(ID_BLOCO)
);

CREATE TABLE IF NOT EXISTS SERRAGEM_BLOCO (
    ID_SERRAGEM INT AUTO_INCREMENT PRIMARY KEY,
    ID_BLOCO INT NOT NULL,
    DATA_SERRAGEM DATETIME,
    QUANTIDADE_CHAPAS_GERADAS INT,
    FOREIGN KEY (ID_BLOCO) REFERENCES BLOCOS(ID_BLOCO)
);

-- Inserir usuário admin padrão
INSERT IGNORE INTO USUARIOS (NOME_USUARIO, SENHA, ATIVO) VALUES ('admin', 'admin', 1);

-- Verificar se foi criado
SELECT * FROM USUARIOS;

-- Mostrar todas as tabelas criadas
SHOW TABLES; 